# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X main.artifactArch={{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - name: speakeasy
    tap:
      owner: speakeasy-api
      name: homebrew-tap
    homepage: https://www.speakeasyapi.dev
    description: The Speakeasy CLI for interacting with the Speakeasy Platform
    license: Apache-2.0
    test: |
      system "#{bin}/speakeasy --version"
  - name: speakeasy@{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    tap:
      owner: speakeasy-api
      name: homebrew-tap
    homepage: https://www.speakeasyapi.dev
    description: The Speakeasy CLI for interacting with the Speakeasy Platform
    license: Apache-2.0
    test: |
      system "#{bin}/speakeasy --version"
